services:
  postgres:
    image: postgres:17

    container_name: listoria-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: listoria
      POSTGRES_PASSWORD: listoria
      POSTGRES_DB: listoria

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listoria -d listoria"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: